### PR TITLE
Hotfix, dynamic files created by backend moved out of plugin directory

### PR DESCRIPTION
**Pull request by sleiban**
Files created dynamically by the backend causes the plugin to stop functioning because the files are not in the manifest file. Issure #41

### CODE REVIEW

**Comment by sleiban** [comment]
Hi, @srclosson! Seems like my pr is blocked: "Build is blocked, please, contact repo admin in order to proceed". Could you help me please?

**Comment by srclosson** [comment]
Will try to look today. I'm in holidays and recovering from surgery, so hoping to be able to get to it today, but wanted to set expectations. 🙂

**Comment by sleiban** [comment]
No rush! Please, take your time to get well! I hope you get well soon

**Comment by srclosson** [comment]
@sleiban Okay, I've approved the build. I'm trying to get another dev on this project, so it's not blocking while I'm away. Question: I'm curious about how you made these changes? Were they are config changes in visual studio?

**Comment by sleiban** [comment]
@srclosson, you were right there was something amiss. The line endings were changed. A new commit to fix this has been added.
There are now 2 config files for logging, one for linux/macos and one for windows. The dachboardmapping.db file is moved outside the directory of the plugin. Details in the readme.

**Review by srclosson — APPROVED** [review]
Nice work @sleiban. I get it. LGTM and I'll release.

**Pull request merged**
